services:
  NBK:
    build:
      context: .
      dockerfile: build_scripts/docker/Dockerfile
    image: nerdbarkaraoke:local
    container_name: nerdBarKaraoke
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
    command: >
      -u ${ADDRESS}
      --admin-password ${ADMIN_PASSWORD}
    volumes:
      - ./songs:/app/pikaraoke-songs      
      - ./data:/home/pikaraoke/.pikaraoke
    ports:
      - "5555:5555"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - NBK
