services:
  nerdBar-Karaoke:
    build:
      context: .
      dockerfile: build_scripts/docker/Dockerfile
    image: pikaraoke:local
    container_name: nerdBarKaraoke
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
    command: >
      -u ${ADDRESS}
      --admin-password ${ADMIN_PASSWORD}
    volumes:
      - ./songs:/app/pikaraoke-songs      
      - ./data:/home/pikaraoke/.pikaraoke
    ports:
      - "5555:5555"
    restart: unless-stopped
    network_mode: bridge
